# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'minitest', '~> 5'
  gem 'rake'
  gem 'rubocop', require: false
  gem 'rubocop-minitest', require: false
end
